version: '3.8'

services:
  # Eureka Server
  eureka-server:
    image: eurekaserveur:latest
    build:
      context: ./EurekaServeur
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - app-network

  # Gateway Service
  gateway:
    image: gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - SERVER_PORT=8088
      - SPRING_APPLICATION_NAME=gateway
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
    networks:
      - app-network
    depends_on:
      - eureka-server

  # MailBox Service
  mailbox:
    image: mailbox:latest
    build:
      context: ./MailBox
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      - SERVER_PORT=8086
      - SPRING_APPLICATION_NAME=MailBox
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/MailBoxDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - app-network
    depends_on:
      - eureka-server
      - db

  # Mail Service
  mail:
    image: mail:latest
    build:
      context: ./Mail
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_APPLICATION_NAME=Mail
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/MailDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - app-network
    depends_on:
      - eureka-server
      - db

  # User Service
  user:
    image: user:latest
    build:
      context: ./User
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=User
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/UserrrDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - app-network
    depends_on:
      - eureka-server
      - db

  # MySQL Database  
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GestionEmailDB
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
