version: '3.8'

services:
  # Gateway Service
  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8088:8088"
    environment:
      - SPRING_APPLICATION_NAME=Gateway
      - SERVER_SERVLET_CONTEXT_PATH=/Gateway
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # Eureka Server
  eureka-server:
    image: eureka-server:latest
    build:
      context: .
      dockerfile: Dockerfile.eureka
    ports:
      - "8761:8761"

  # MailBox Service
  # mailbox:
  #   image: mailbox-service:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mailbox
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - SPRING_APPLICATION_NAME=MailBox
  #     - SERVER_SERVLET_CONTEXT_PATH=/MailBox
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/MailBoxDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=
  #     - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # Mail Service
  mail:
    image: mail-service:latest
    build:
      context: .
      dockerfile: Dockerfile.mail
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=Mail
      - SERVER_SERVLET_CONTEXT_PATH=/Mail
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/MailDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # User Service
  user:
    image: user-service:latest
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=User
      - SERVER_SERVLET_CONTEXT_PATH=/User
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/UserrrDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GestionEmailDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
