version: '3.8'

services:
  # Gateway Service
  gateway:
    image: gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - SPRING_APPLICATION_NAME=Gateway
      - SERVER_SERVLET_CONTEXT_PATH=/Gateway
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # Eureka Server
  eureka-server:
    image: eurekaserveur:latest
    build:
      context: ./EurekaServeur
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  # MailBox Service
  mailbox:
    image: mailbox:latest
    build:
      context: ./MailBox
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      - SPRING_APPLICATION_NAME=MailBox
      - SERVER_SERVLET_CONTEXT_PATH=/MailBox
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/MailBoxDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # Mail Service
  mail:
    image: mail:latest
    build:
      context: ./Mail
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=Mail
      - SERVER_SERVLET_CONTEXT_PATH=/Mail
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/MailDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # User Service
  user:
    image: user:latest
    build:
      context: ./User
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=User
      - SERVER_SERVLET_CONTEXT_PATH=/User
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/UserrrDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # MySQL Database  
  db:
  image: mysql:8.0
  container_name: mysql-container
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: GestionEmailDB
  ports:
    - "3307:3306"  # Host port 3307 mapped to container port 3306
  volumes:
    - mysql_data:/var/lib/mysql

